package no.vaagenpressing.fixture;
import org.springframework.data.jpa.repository.JpaRepository;

/** Data access for {@link Fixture}. Implementation is generated by Spring Data. */
public interface FixtureRepository extends JpaRepository<Fixture, Integer> {
}
