package no.vaagenpressing.team;
import org.springframework.data.jpa.repository.JpaRepository;

/** Data access for {@link Team}. Implementation is generated by Spring Data. */
public interface TeamRepository extends JpaRepository<Team, Integer> {

}
