spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/vaagenpressing
spring.datasource.username=vaagen
spring.datasource.password=${DB_PASSWORD:vaagen_dev}

spring.jpa.open-in-view=false